export const videos =[

    {
        id:1,
        categoriesId:3,
        titre:"bienvenue",
        description:"bla bla",
        image:require('../images/1.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:2,
        categoriesId:5,
        titre:"bienvenue chez les boss",
        description:"Personne ne nait null mais tout le monde l'est.",
        image:require('../images/2.jpeg'),
        tendance:1,
        date:"12/02/2002",
    },
    {
        id:3,
        categoriesId:2,
        titre:"I bon",
        description:"Expression trés populaire en martinique et aussi dans les antilles.",
        image:require('../images/3.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:4,
        categoriesId:2,
        titre:"Mada",
        description:"commune de Monsieur Million Stéphen ",
        image:require('../images/4.jpeg'),
        tendance:1,
        date:"12/02/2002",
    },
    {
        id:5,
        categoriesId:2,
        titre:"Imfpa",
        description:"Centre de dev personnel ",
        image:require('../images/5.jpeg'),
        tendance:1,
        date:"12/02/2002",
    },
    {
        id:6,
        categoriesId:2,
        titre:"Devenir dév",
        description:"Developper web, un metier d'avenir",
        image:require('../images/6.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:7,
        categoriesId:2,
        titre:"Bien être",
        description:"bla bla, pendant que le loup n'y est pas !",
        image:require('../images/7.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:8,
        categoriesId:2,
        titre:"Savoir être",
        description:"la chasse est ouverte",
        image:require('../images/8.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:9,
        categoriesId:2,
        titre:"Popo",
        description:"La nature le seul remede sur terre.",
        image:require('../images/9.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },
    {
        id:10,
        categoriesId:2,
        titre:"Playa",
        description:"l'été offre ces belles plages cette période festival",
        image:require('../images/10.jpeg'),
        tendance:0,
        date:"12/02/2002",
    },

]